server:
  port: ${PORT}

spring:
  mail:
      host: smtp.gmail.com
      port: 587
      username: ${SMTP_USER}
      password: ${SMTP_PASS}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-time: ${JWT_ACCESS_TIME}
  refresh-time: ${JWT_REFRESH_TIME}

client:
  client-url: ${CLIENT_URL}